liip_imagine:
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"
    filter_sets:
        sylius_shop_product_thumbnail:
            filters:
                thumbnail:
                    { size: [520, 520], mode: inset, allow_upscale: true }
        sylius_shop_product_tiny_thumbnail:
            filters:
                thumbnail:
                    { size: [128, 128], mode: inset, allow_upscale: true }
        sylius_shop_product_small_thumbnail:
            filters:
                thumbnail:
                    { size: [300, 300], mode: inset, allow_upscale: true }
        sylius_shop_product_large_thumbnail:
            filters:
                thumbnail:
                    { size: [1100, 1100], mode: inset, allow_upscale: true }
