sylius_shop:
    checkout_resolver:
        pattern: /checkout/.+
        route_map:
            empty_order:
                route: sylius_shop_cart_summary
            cart:
                route: sylius_shop_checkout_select_shipping
            shipping_selected:
                route: sylius_shop_checkout_select_payment
            shipping_skipped:
                route: sylius_shop_checkout_select_payment
            payment_selected:
                route: sylius_shop_checkout_address
            payment_skipped:
                route: sylius_shop_checkout_address
            addressed:
                route: sylius_shop_checkout_complete
