sylius_shop:
    checkout_resolver:
        pattern: /checkout/.+
        route_map:
            empty_order:
                route: sylius_shop_cart_summary
            loggedin:
                route: sylius_shop_checkout_register
            registered:
                route: sylius_shop_checkout_select_shipping
            cart:
                route: sylius_shop_checkout_login
            shipping_selected:
                route: sylius_shop_checkout_select_payment
            shipping_skipped:
                route: sylius_shop_checkout_select_payment
            payment_selected:
                route: sylius_shop_checkout_address
            payment_skipped:
                route: sylius_shop_checkout_address
            addressed:
                route: sylius_shop_checkout_complete
            address_skipped:
                route: sylius_shop_checkout_complete
