winzou_state_machine:
    sylius_order_checkout:
        class: "%sylius.model.order.class%"
        property_path: checkoutState
        graph: sylius_order_checkout
        state_machine_class: "%sylius.state_machine.class%"
        states:
            cart: ~
            loggedin: ~
            registered: ~
            registration_skipped: ~
            shipping_selected: ~
            shipping_skipped: ~
            payment_skipped: ~
            payment_selected: ~
            addressed: ~
            address_skipped: ~
            completed: ~
        transitions:
            login:
                from:
                    [
                        cart,
                        loggedin,
                        registered,
                        registration_skipped,
                        addressed,
                        address_skipped,
                        shipping_selected,
                        shipping_skipped,
                        payment_selected,
                        payment_skipped,
                    ]
                to: loggedin
            skip_registration:
                from: [loggedin]
                to: registration_skipped
            register:
                from:
                    [
                        loggedin,
                        registered,
                        registration_skipped,
                        addressed,
                        address_skipped,
                        shipping_selected,
                        shipping_skipped,
                        payment_selected,
                        payment_skipped,
                    ]
                to: registered
            skip_shipping:
                from: [registered, registration_skipped]
                to: shipping_skipped
            select_shipping:
                from:
                    [
                        loggedin,
                        addressed,
                        registered,
                        registration_skipped,
                        shipping_selected,
                        shipping_skipped,
                        payment_selected,
                        payment_skipped,
                    ]
                to: shipping_selected
            skip_payment:
                from: [shipping_selected, shipping_skipped]
                to: payment_skipped
            select_payment:
                from:
                    [
                        addressed,
                        payment_selected,
                        shipping_skipped,
                        shipping_selected,
                    ]
                to: payment_selected
            address:
                from:
                    [
                        addressed,
                        shipping_selected,
                        shipping_skipped,
                        payment_selected,
                        payment_skipped,
                    ]
                to: addressed
            skip_address:
                from: [payment_selected, payment_skipped]
                to: address_skipped
            complete:
                from: [addressed, address_skipped]
                to: completed
        callbacks:
            after:
                sylius_process_cart:
                    on:
                        [
                            "login",
                            "register",
                            "skip_registration",
                            "select_shipping",
                            "address",
                            "skip_address",
                            "select_payment",
                            "skip_shipping",
                            "skip_payment",
                        ]
                    do: ["@sylius.order_processing.order_processor", "process"]
                    args: ["object"]
                sylius_create_order:
                    on: ["complete"]
                    do: ["@sm.callback.cascade_transition", "apply"]
                    args: ["object", "event", "'create'", "'sylius_order'"]
                sylius_save_checkout_completion_date:
                    on: ["complete"]
                    do: ["object", "completeCheckout"]
                    args: ["object"]
                sylius_skip_address:
                    on: ["select_payment"]
                    do: ["@sylius.state_resolver.order_checkout", "resolve"]
                    args: ["object"]
                    priority: 1
                sylius_skip_shipping:
                    on: ["register"]
                    do: ["@sylius.state_resolver.order_checkout", "resolve"]
                    args: ["object"]
                    priority: 1
                sylius_skip_payment:
                    on: ["select_shipping"]
                    do: ["@sylius.state_resolver.order_checkout", "resolve"]
                    args: ["object"]
                    priority: 1
                sylius_skip_registration:
                    on: ["login"]
                    do: ["@sylius.state_resolver.order_checkout", "resolve"]
                    args: ["object"]
                    priority: 1
                sylius_control_payment_state:
                    on: ["complete"]
                    do: ["@sylius.state_resolver.order_payment", "resolve"]
                    args: ["object"]
                sylius_control_shipping_state:
                    on: ["complete"]
                    do: ["@sylius.state_resolver.order_shipping", "resolve"]
                    args: ["object"]
