app_shop_aboutus:
    path: /aboutus
    methods: [GET]
    defaults:
        _controller: app.controller.shop.aboutus::indexAction
app_shop_shipinfo:
    path: /shipinfo
    methods: [GET]
    defaults:
        _controller: app.controller.shop.shipinfo::indexAction
app_shop_policy:
    path: /policy
    methods: [GET]
    defaults:
        _controller: app.controller.shop.policy::indexAction
app_shop_download_list:
    path: /download
    methods: [GET]
    defaults:
        _controller: app.controller.shop.download::listAction
app_shop_download_show:
    path: /downloadables/{code}
    methods: [GET]
    defaults:
        _controller: app.controller.shop.download::showAction
app_shop_download:
    path: /download/{code}
    methods: [GET]
    defaults:
        _controller: app.controller.shop.download::downloadAction
