app_shop_aboutus:
    path: /aboutus
    methods: [GET]
    defaults:
        _controller: app.controller.shop.aboutus::indexAction
app_shop_shipinfo:
    path: /shipinfo
    methods: [GET]
    defaults:
        _controller: app.controller.shop.shipinfo::indexAction
app_shop_policy:
    path: /policy
    methods: [GET]
    defaults:
        _controller: app.controller.shop.policy::indexAction
app_shop_download_list:
    path: /download
    methods: [GET]
    defaults:
        _controller: app.controller.shop.download::listAction
app_shop_download_order_show:
    path: /order-downloadables/{token}
    methods: [GET]
    defaults:
        _controller: app.controller.shop.download::showOrderAction
app_shop_download:
    path: /download/{code}
    methods: [GET]
    defaults:
        _controller: app.controller.shop.download::downloadAction
app_shop_cdek_service:
    path: /cdek/service
    methods: [GET, POST]
    defaults:
        _controller: app.controller.shop.cdek::serviceAction
app_shop_cdek_template:
    path: /cdek/template
    methods: [GET]
    defaults:
        _controller: app.controller.shop.cdek::templateAction

# Override the AJAX user check to use our custom repository
sylius_shop_ajax_user_check_action:
    path: /{_locale}/check
    methods: [GET]
    defaults:
        _controller: app.controller.shop.user_check::checkAction
        _format: json
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

app_taxon_title:
    path: /by-slug/{slug}
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxon:showAction
        _sylius:
            template: $template
            repository:
                method: findOneBySlug
                arguments:
                    - $slug
                    - "expr:service('sylius.context.locale').getLocaleCode()"
    requirements:
        slug: .+
